# Generated by Django 3.2.18 on 2023-05-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('service', models.CharField(max_length=50)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('vulnerability', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=50)),
            ],
        ),
    ]
