# Generated by Django 3.2.18 on 2023-05-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('services', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=50)),
            ],
        ),
    ]
